### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by gazalk** [BioHaskell/hPDB#3]
Hi,

I'm a novice for Haskell, so I'm not familiar with the procedures. Could you please help me with the following error. I'm making installation on Ubuntu 16.04 with GHC version 7.10.3. 

`[53 of 60] Compiling Bio.PDB.Structure.Neighbours ( Bio/PDB/Structure/Neighbours.hs, dist/build/Bio/PDB/Structure/Neighbours.o )

Bio/PDB/Structure/Neighbours.hs:22:43:
    Couldn't match type ‘Vector3’
                   with ‘linear-1.20.7:Linear.V3.V3 Double’
    Expected type: Oct.Vector3
      Actual type: Vector3
    In the expression: cvec
    In the expression: (cvec, at)

Bio/PDB/Structure/Neighbours.hs:30:16:
    Couldn't match type ‘linear-1.20.7:Linear.V3.V3 Double’
                   with ‘Vector3’
    Expected type: AtomOctree -> Double -> Vector3 -> [(Vector3, Atom)]
      Actual type: Oct.Octree Atom
                   -> Double
                   -> linear-1.20.7:Linear.V3.V3 Double
                   -> [(linear-1.20.7:Linear.V3.V3 Double, Atom)]
    In the expression: Oct.withinRange
    In an equation for ‘findInRadius’: findInRadius = Oct.withinRange

Bio/PDB/Structure/Neighbours.hs:34:16:
    Couldn't match type ‘linear-1.20.7:Linear.V3.V3 Double’
                   with ‘Vector3’
    Expected type: AtomOctree -> Vector3 -> Maybe (Vector3, Atom)
      Actual type: Oct.Octree Atom
                   -> linear-1.20.7:Linear.V3.V3 Double
                   -> Maybe (linear-1.20.7:Linear.V3.V3 Double, Atom)
    In the expression: Oct.nearest
    In an equation for ‘findNearest’: findNearest = Oct.nearest
cabal: Error: some packages failed to install:
hPDB-1.2.0.10 failed during the building phase. The exception was:
ExitFailure 1
hPDB-examples-1.2.0.8 depends on hPDB-1.2.0.10 which failed to install.
`

**Comment by mgajda** [comment]
I have added `stack.yml` as known working configuration.
Now `stack install` will work. Unfortunately, I am unable to reproduce your error.
Can we share the `tmate` session or something to let me see?

**Comment by kanishka-azimi** [comment]
@gazalk I can confirm that a clean clone and stack setup and stack build successfully builds for me.

Please respond or close this issue if you are no longer interested. I hope you did find some resolution to the work you were attempting, regardless of whether hPDB helped.

**Comment by gazalk** [comment]
After this commit: https://github.com/BioHaskell/hPDB/commit/30c490c7558498f0388250b6a40e988907c171e8, there were no errors anymore. It does give a proper installation for me now.
